---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tt-k8s-driver-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - driver.tenstorrent.com
  resources:
  - tenstorrentdriverpolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - driver.tenstorrent.com
  resources:
  - tenstorrentdriverpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - firmware.tenstorrent.com
  resources:
  - tenstorrentfirmwarepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - firmware.tenstorrent.com
  resources:
  - tenstorrentfirmwarepolicies/status
  verbs:
  - get
  - patch
  - update
