//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainPolicy) DeepCopyInto(out *DrainPolicy) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.DeleteEmptyDir != nil {
		in, out := &in.DeleteEmptyDir, &out.DeleteEmptyDir
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainPolicy.
func (in *DrainPolicy) DeepCopy() *DrainPolicy {
	if in == nil {
		return nil
	}
	out := new(DrainPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverNodeStatus) DeepCopyInto(out *DriverNodeStatus) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverNodeStatus.
func (in *DriverNodeStatus) DeepCopy() *DriverNodeStatus {
	if in == nil {
		return nil
	}
	out := new(DriverNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverSummary) DeepCopyInto(out *DriverSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverSummary.
func (in *DriverSummary) DeepCopy() *DriverSummary {
	if in == nil {
		return nil
	}
	out := new(DriverSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallerOverride) DeepCopyInto(out *InstallerOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallerOverride.
func (in *InstallerOverride) DeepCopy() *InstallerOverride {
	if in == nil {
		return nil
	}
	out := new(InstallerOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenstorrentDriverPolicy) DeepCopyInto(out *TenstorrentDriverPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenstorrentDriverPolicy.
func (in *TenstorrentDriverPolicy) DeepCopy() *TenstorrentDriverPolicy {
	if in == nil {
		return nil
	}
	out := new(TenstorrentDriverPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenstorrentDriverPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenstorrentDriverPolicyList) DeepCopyInto(out *TenstorrentDriverPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenstorrentDriverPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenstorrentDriverPolicyList.
func (in *TenstorrentDriverPolicyList) DeepCopy() *TenstorrentDriverPolicyList {
	if in == nil {
		return nil
	}
	out := new(TenstorrentDriverPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenstorrentDriverPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenstorrentDriverPolicySpec) DeepCopyInto(out *TenstorrentDriverPolicySpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.UpgradePolicy.DeepCopyInto(&out.UpgradePolicy)
	if in.Installer != nil {
		in, out := &in.Installer, &out.Installer
		*out = new(InstallerOverride)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenstorrentDriverPolicySpec.
func (in *TenstorrentDriverPolicySpec) DeepCopy() *TenstorrentDriverPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TenstorrentDriverPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenstorrentDriverPolicyStatus) DeepCopyInto(out *TenstorrentDriverPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]DriverNodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenstorrentDriverPolicyStatus.
func (in *TenstorrentDriverPolicyStatus) DeepCopy() *TenstorrentDriverPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TenstorrentDriverPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePolicy) DeepCopyInto(out *UpgradePolicy) {
	*out = *in
	in.Drain.DeepCopyInto(&out.Drain)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePolicy.
func (in *UpgradePolicy) DeepCopy() *UpgradePolicy {
	if in == nil {
		return nil
	}
	out := new(UpgradePolicy)
	in.DeepCopyInto(out)
	return out
}
